
_target_: ccmm.matching.matcher.FrankWolfeSynchronizedMatcher
name: 'frank_wolfe'
permutation_spec: ??
max_iter: 200 # TODO: switch back
initialization_method: 'sinkhorn' # 'sinkhorn', 'identity' or 'random'
verbose: False
