data_path: ${oc.env:PROJECT_ROOT}/data/cifar100_tasks
name: CIFAR100_TASKS
num_classes: 100
in_channels: 3

transform_func:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
