data_path: ${oc.env:PROJECT_ROOT}/data
name: CIFAR100
num_classes: 100
in_channels: 3
input_shape:
  - 1
  - 3
  - 32
  - 32

train:
  _target_: torchvision.datasets.CIFAR100
  root: ${dataset.data_path}
  train: True
  download: True
  transform: ${dataset.train_transform}

test:
  _target_: torchvision.datasets.CIFAR100
  root: ${dataset.data_path}
  train: False
  download: True
  transform: ${dataset.test_transform}

train_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomResizedCrop
      size: 32
      scale:
        - 0.8
        - 1.2
    - _target_: torchvision.transforms.RandomRotation
      degrees: 30
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

test_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
