
_target_: ccmm.matching.merger.FrankWolfeSynchronizedMerger
name: 'frank_wolfe'
permutation_spec: ??
max_iter: 200
average_in_universe: True
initialization_method: 'identity' # 'sinkhorn', 'identity' or 'random'
keep_soft_perms: False
