# metadata specialised for each experiment
core:
  project_name: cycle-consistent-model-merging
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  version: 0.0.1
  tags:
    - train_tasks

defaults:
  - hydra: default
  - nn: n_tasks
  - train: resnet
  - dataset: cifar100_tasks
  - _self_
