name: ResNet
widen_factor: ??
depth: 50
num_classes: ${dataset.num_classes}

model_identifier: ${model.name}${model.depth}

permutation_spec_builder:
  _target_: ccmm.matching.permutation_spec.AutoPermutationSpecBuilder
