name: ResNet
widen_factor: 2
depth: 22

model_identifier: ${model.name}${model.depth}_${model.widen_factor}  # _bn

permutation_spec_builder:
  _target_: ccmm.matching.permutation_spec.ResNet20PermutationSpecBuilder
