seed_index: 1

output_path: ${oc.env:PROJECT_ROOT}/output
dataset_path: ${oc.env:PROJECT_ROOT}/data

dummy_permutations: True

model_name: MLP
dataset: MNIST

sync_method: 'spectral' # 'stiefel', 'spectral', 'nmfSync'

model_seeds:
  - 1
  - dummy_b
  - dummy_c
  # - 4
  # - 5

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  precision: 32

num_interpolation_steps: 3

datasets:
  train:
    _target_: torchvision.datasets.MNIST
    root: ${dataset_path}
    train: True
    download: True
    transform: ${transform}

  test:
    _target_: torchvision.datasets.MNIST
    root: ${dataset_path}
    train: False
    download: True
    transform: ${transform}

permutation_spec_builder:
  _target_: ccmm.matching.permutation_spec.MLPPermutationSpecBuilder
  num_hidden_layers: 4

transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.1307]
        std: [0.3081]

batch_size: 5000
num_workers: 14

model_identifier: ${model_name}
model_info_path: ${output_path}/${dataset}/${model_name}

permutations_path: ${path:${oc.env:PROJECT_ROOT}/output/${dataset}/match_then_sync/${sync_method}/}
results_path: ${path:${oc.env:PROJECT_ROOT}/results/${dataset}/match_then_sync/${sync_method}/}

dummy_permutations_path: ${output_path}/${dataset}/
