seed_index: 1

output_path: ${oc.env:PROJECT_ROOT}/output
dataset_path: ${oc.env:PROJECT_ROOT}/data

model_name: ResNet
widen_factor: 2
depth: 22
dataset: CIFAR10

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  precision: 32

sync_method: 'stiefel' # 'stiefel', 'spectral', 'nmfSync'

model_seeds:
  - 1
  - 2
  - 3

num_interpolation_steps: 3

datasets:
  train:
    _target_: torchvision.datasets.CIFAR10
    root: ${matching.dataset_path}
    train: True
    download: True
    transform: ${matching.transform}

  test:
    _target_: torchvision.datasets.CIFAR10
    root: ${matching.dataset_path}
    train: False
    download: True
    transform: ${matching.transform}

permutation_spec_builder:
  _target_: ccmm.matching.permutation_spec.ResNet20PermutationSpecBuilder

transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

batch_size: 5000
num_workers: 14

model_identifier: ${matching.model_name}_${matching.depth}_${matching.widen_factor}
model_info_path: ${matching.output_path}/${matching.dataset}/${matching.model_identifier}


permutations_path: ${path:${oc.env:PROJECT_ROOT}/output/${matching.dataset}/match_then_sync/${matching.sync_method}/}
results_path: ${oc.env:PROJECT_ROOT}/results/${matching.dataset}/match_then_sync/${matching.sync_method}/
