seed_index: 1

output_path: ${oc.env:PROJECT_ROOT}/output
dataset_path: ${oc.env:PROJECT_ROOT}/data

model_name: ResNet
widen_factor: 2
depth: 22
dataset: CIFAR10


trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  precision: 32

sync_method: null # 'stiefel', 'spectral', 'nmfSync'
use_alternate_diffusion: true

model_seeds:
  - 1
  - 2
  # - 3
  # - 4
  # - 5

num_interpolation_steps: 3

datasets:
  train:
    _target_: torchvision.datasets.CIFAR10
    root: ${dataset_path}
    train: True
    download: True
    transform: ${transform}

  test:
    _target_: torchvision.datasets.CIFAR10
    root: ${dataset_path}
    train: False
    download: True
    transform: ${transform}

permutation_spec_builder:
  _target_: ccmm.matching.weight_matching.ResNet20PermutationSpecBuilder

transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]


batch_size: 5000
num_workers: 14

model_identifier: ${model_name}_${depth}_${widen_factor}
model_info_path: ${output_path}/${dataset}/${model_identifier}

permutations_path: ${path:${oc.env:PROJECT_ROOT}/output/${dataset}/match_and_sync/${sync_method}/}
results_path: ${oc.env:PROJECT_ROOT}/results/${dataset}/match_and_sync/${sync_method}/
