seed_index: 0

output_path: ${oc.env:PROJECT_ROOT}/output
dataset_path: ${oc.env:PROJECT_ROOT}/data

model_name: MLP
dataset: MNIST

model_a_seed: 1
model_b_seed: 2

num_interpolation_steps: 25

datasets:
  train:
    _target_: torchvision.datasets.MNIST
    root: ${dataset_path}
    train: True
    download: True
    transform: ${transform}

  test:
    _target_: torchvision.datasets.MNIST
    root: ${dataset_path}
    train: False
    download: True
    transform: ${transform}

permutation_spec_builder:
  _target_: ccmm.utils.weight_matching.MLPPermutationSpecBuilder
  num_hidden_layers: 4

transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.1307]
        std: [0.3081]

batch_size: 5000
model_identifier: ${model_name}
model_a_info_path: ${output_path}/${dataset}/${model_name}_${model_a_seed}.json
model_b_info_path: ${output_path}/${dataset}/${model_name}_${model_b_seed}.json

results_path: ${oc.env:PROJECT_ROOT}/results/${dataset}
