seed_index: 1

output_path: ${oc.env:PROJECT_ROOT}/output
dataset_path: ${oc.env:PROJECT_ROOT}/data

model_name: ResNet
widen_factor: 2
depth: 22
dataset: CIFAR10

permutation_spec_builder:
  _target_: ccmm.utils.weight_matching.ResNet20PermutationSpecBuilder

# permutation_spec_builder:
#   _target_: ccmm.utils.weight_matching.ResNet50PermutationSpecBuilder

datasets:
  train:
    _target_: torchvision.datasets.CIFAR10
    root: ${dataset_path}
    train: True
    download: True
    transform: ${transform}

  test:
    _target_: torchvision.datasets.CIFAR10
    root: ${dataset_path}
    train: False
    download: True
    transform: ${transform}

transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]


model_a_seed: 1
model_b_seed: 2

num_interpolation_steps: 3


batch_size: 1024
model_identifier: ${model_name}_${depth}_${widen_factor}
model_a_info_path: ${output_path}/${dataset}/${model_identifier}_${model_a_seed}.json
model_b_info_path: ${output_path}/${dataset}/${model_identifier}_${model_b_seed}.json

results_path: ${oc.env:PROJECT_ROOT}/results/${dataset}
