train:
  _target_: torchvision.datasets.CIFAR10
  root: ${nn.data_path}
  train: True
  download: True
  transform: ${nn.dataset.train_transform}

test:
  _target_: torchvision.datasets.CIFAR10
  root: ${nn.data_path}
  train: False
  download: True
  transform: ${nn.dataset.test_transform}

train_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomCrop
      size: 32
      padding: 4
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]


test_transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
